resources:
  repositories:
  - repository: self
    trigger:
      branches:
        include:
        - master
      paths:
        include:
        - /*
        exclude:
        - pipelines/*
        - scripts/*
        - README.md
        - .gitignore
        - vscode-defaults
  - repository: aks-commander
    type: github
    name: rhummelmose/aks-commander
    endpoint: rhummelmose
    trigger: none

variables:
- group: cosmocats

stages:
- stage: stage_build_push
  displayName: Build and push image
  jobs:
  - job: job_build_push
    displayName: Build and push image
    pool:
      vmImage: "ubuntu-latest"
    steps:
    - task: Docker@2
      displayName: Build and push image
      inputs:
        command: buildAndPush
        containerRegistry: acr-service-connection-rh-gbb-cloud-native
        repository: cosmocats
        tags: |
          $(Build.SourceVersion)
- stage: stage_deploy
  displayName: Deploy to k8s
  jobs:
  - job: Deploy
    displayName: Deploy to k8s
    pool:
      vmImage: "ubuntu-latest"
    steps:
    - checkout: self
    - checkout: aks-commander
    - template: templates/tokenize.yml
    - template: templates/deploy.yml
