trigger:
- master

resources:
- repo: self

variables:
- group: cosmocats
- group: deployment-configuration
- name: AZDEV_BUILD_SOURCE_VERSION
  value: $(Build.SourceVersion)

stages:
- stage: BuildPush
  displayName: Build and push image
  jobs:  
  - template: templates/build.yml
- stage: Deploy
  displayName: Deploy to K8s
  jobs:
  - template: templates/deploy.yml
