trigger:
- master

resources:
- repo: self

variables:
- group: "cosmocats"
- name: "AZDEV_BUILD_SOURCE_VERSION"
  value: $(Build.SourceVersion)

stages:
- stage: BuildPush
  displayName: Build and push image
  jobs:  
  - job: BuildPush
    displayName: Build and push image
    pool:
      vmImage: "ubuntu-latest"
    steps:
    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        containerRegistry: acr-service-connection-rh-gbb-cloud-native
        repository: cosmocats
        tags: |
          $(AZDEV_BUILD_SOURCE_VERSION)
- stage: Deploy
  displayName: Deploy to K8s
  jobs:
  - job: Deploy
    displayName: Deploy to K8s
    pool:
      vmImage: "ubuntu-latest"
    steps:
    - task: Bash@3
      inputs:
        filePath: "scripts/tokenize.sh"
      env:
        COSMOCATS_COSMOSDB_KEY: $(COSMOCATS_COSMOSDB_KEY)
    - task: AzureCLI@2
      displayName: Azure CLI
      inputs:
        azureSubscription: arm-service-connection-rh-subcription-vse-950dkk
        scriptType: bash
        scriptPath: scripts/deploy.sh
