trigger:
- master

resources:
- repo: self

variables:
- group: cosmocats

stages:
- stage: stage_build_push
  displayName: Build and push image
  jobs:
  - job: job_build_push
    displayName: Build and push image
    pool:
      vmImage: "ubuntu-latest"
    steps:
    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        containerRegistry: acr-service-connection-rh-gbb-cloud-native
        repository: cosmocats
        tags: |
          $(AZDEV_BUILD_SOURCE_VERSION)
- stage: stage_deploy
  displayName: Deploy to K8s
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: "ubuntu-latest"
    steps:
    - template: templates/tokenize.yml
    - template: templates/deploy.yml
