resources:
  repositories:
  - repository: self
  - repository: aks-commander
    type: github
    name: rhummelmose/aks-commander
    endpoint: rhummelmose

stages:
- stage: Test
  displayName: Test
  jobs:
  - job: Test
    displayName: Test
    pool:
      vmImage: "ubuntu-latest"
    steps:
    - checkout: self
    - checkout: aks-commander
    - task: AzureCLI@2
      displayName: Azure CLI
      inputs:
        azureSubscription: arm-service-connection-rh-subcription-vse-950dkk
        addSpnToEnvironment: true
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
            deployment_targets=$(bash aks-commander/scripts/deployment_targets_for_application.sh "$BUILD_REPOSITORY_URI")
            bash cosmocats/scripts/deploy_multiple.sh "$deployment_targets"
