trigger:
- master

resources:
- repo: self

stages:
- stage: Test
  displayName: Test
  jobs:
  - job: Test
    displayName: Test
    pool:
      vmImage: "ubuntu-latest"
    resources:
    - repositories:
      - repository: aks-commander
        type: github
        name: rhummelmose/aks-commander
    steps:
    - script: pwd && ls -la /
      displayName: ls -la
