trigger:
- master

resources:
- repo: self

stages:
- stage: Test
  displayName: Test
  resources:
  - repositories:
    - repository: aks-commander
      type: github
      name: rhummelmose/aks-commander
  jobs:
  - job: Test
    displayName: Test
    pool:
      vmImage: "ubuntu-latest"
    steps:
    - script: pwd && ls -la /
      displayName: ls -la
