trigger:
- master

resources:
- repo: self

stages:
- stage: Test
  displayName: Test
  jobs:
  - job: Test
    displayName: Test
    pool:
      vmImage: "ubuntu-latest"
    steps:
    - checkout: self
    - checkout: github://rhummelmose/aks-commander
    - script: pwd && ls -la / && ls -la . && ls -la ../
      displayName: sesame
